version: "3.8"

services:
  mongo-mep:
    image: mongo:5.0
    container_name: mongo-mep
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - oai-mep-net
    volumes:
      - mongo_data:/data/db

  postgres-kong:
    image: postgres:14-alpine
    container_name: postgres-kong
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    ports:
      - "5432:5432"
    networks:
      - oai-mep-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kong-migration:
    image: kong:2.8-alpine
    container_name: kong-migration
    depends_on:
      - postgres-kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres-kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    networks:
      - oai-mep-net
    command: kong migrations bootstrap

  kong-mep:
    image: kong:2.8-alpine
    container_name: kong-mep
    depends_on:
      kong-migration:
        condition: service_started
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres-kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
    networks:
      - oai-mep-net
    stdin_open: true
    tty: true

  oai-mep:
    image: oaisoftwarealliance/oai-mep:latest
    container_name: oai-mep
    depends_on:
      - mongo-mep
      - kong-mep
    environment:
      MONGO_DB_URL: mongodb://root:root@mongo-mep:27017/oai_mep?authSource=admin
      KONG_ADMIN_URL: http://kong-mep:8001
      MEP_NAME: oai-mep
    ports:
      - "8090:8090"
    networks:
      - oai-mep-net

networks:
  oai-mep-net:
    driver: bridge

volumes:
  mongo_data:
  postgres_data:
